spring:
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
              - authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE

---

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

---

transaction-service:
  url: http://transaction-update-service:3000/
user-service:
  url: http://user-service:3000/
account-link-service:
  url: http://account-link-service:3000/
account-service:
  url: http://account-update-service:3000/