spring:
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://mm-eureka:8761/eureka/

---

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200, http://localhost:8081"
            allowedHeaders:
              - content-type
              - authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE