spring:
  application:
    name: Gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8080
debug: true
eureka:
  client:
    register-with-eureka: false

---

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
