spring:
  cloud:
    discovery:
      enabled: false

---

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200, http://localhost:8081"
            allowedHeaders:
              - content-type
              - authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE