spring:
  application:
    name: Gateway
  profiles:
    active: local
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
    discovery:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
