spring:
  application:
    name: Gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8080

---

spring:
  boot:
    admin:
      client:
        url: http://localhost:8079

---

spring:
  config:
    activate:
      on-profile: dev, prod
  boot:
    admin:
      client:
        url: //moneymaker-admin-service:8079

---

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
