spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        service-labels:
          discoverable: true
      enabled: true
      reload:
        strategy: restart_context
        enabled: true
eureka:
  client:
    enabled: false
management:
  endpoint:
    restart:
      enabled: true