spring:
  cloud:
    discovery:
      enabled: false

---

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
              - authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
        add-to-simple-url-handler-mapping: true

---

spring:
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8079

---

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO