spring:
  application:
    name: Gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8080

---

spring:
  cloud:
    gateway:
      routes:
        - id: budgets
          uri: lb://OAKA/
          predicates:
            - Path=/v1/budgets/**
        - id: accounts
          uri: lb://SETZER/
          predicates:
            - Path=/v1/accounts/**
        - id: accounts
          uri: lb://SETZER/
          predicates:
            - Path=/v1/account-types/**
        - id: budgetCategories
          uri: lb://OAKA/
          predicates:
            - Path=/v1/budgetCategories/**
        - id: budgetTypes
          uri: lb://OAKA/
          predicates:
            - Path=/v1/budgetTypes/**
        - id: frequencyTypes
          uri: lb://OAKA/
          predicates:
            - Path=/v1/frequencyTypes/**
        - id: transactions
          uri: lb://OAKA/
          predicates:
            - Path=/v1/transactions/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

